"use client";
import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

import Sidebar from "./components/Sidebar";
import Nav from "./components/Nav";
const inter = `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');`;

// metadata를 컴포넌트 밖으로 이동시켜서 따로 export
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <Nav />
        {children}
      </body>
    </html>
  );
}
